// supabase/functions/_shared/errors.ts
// Mirror de packages/shared/src/errors.ts pour Deno (pas d'import npm en Edge Functions)
// Toute Edge Function retourne { ok: false, error: { code, message, cause?, http, retryable, entity? } }

import { corsHeaders } from './cors.ts'

export type ErrorCode =
  | 'VAL_INVALID_INPUT' | 'VAL_MISSING_FIELD'
  | 'AUTH_REQUIRED' | 'AUTH_INVALID_CREDENTIALS' | 'AUTH_LOCKED'
  | 'AUTH_2FA_REQUIRED' | 'AUTH_2FA_INVALID' | 'AUTH_EMAIL_NOT_VERIFIED' | 'AUTH_SESSION_EXPIRED'
  | 'PERM_DENIED'
  | 'SEC_TENANT_VIOLATION' | 'SEC_RATE_LIMITED' | 'SEC_WEBHOOK_SIGNATURE' | 'SEC_WITHDRAWAL_LOCKED' | 'SEC_CAPTCHA_FAILED'
  | 'SLOT_ALREADY_BOOKED' | 'SLOT_NOT_AVAILABLE' | 'CANCEL_TOO_LATE' | 'PRO_MONTHLY_LIMIT'
  | 'APPOINTMENT_NOT_ARRIVED' | 'SCHEDULE_CONFLICT' | 'SCHEDULE_HAS_APPOINTMENTS'
  | 'PRESCRIPTION_REQUIRED' | 'PRESCRIPTION_EXPIRED' | 'PRESCRIPTION_ALREADY_SHARED'
  | 'PRESCRIPTION_NOT_SIGNABLE' | 'PROFESSIONAL_NOT_VERIFIED' | 'SHARE_EXPIRED' | 'PDF_GENERATION_FAILED'
  | 'STOCK_INSUFFICIENT' | 'STOCK_CHANGED' | 'PHARMACY_CLOSED_FOR_RESERVATIONS' | 'PHARMACY_NOT_VERIFIED'
  | 'PREPARATION_BLOCKED' | 'WITHDRAWAL_CODE_INVALID' | 'WITHDRAWAL_LOCKED'
  | 'RESERVATION_EXPIRED' | 'CANCEL_NOT_ALLOWED' | 'CODE_POOL_EXHAUSTED'
  | 'MEMBER_NOT_VERIFIED' | 'CEILING_EXCEEDED' | 'COVERAGE_RULE_NOT_FOUND' | 'MEMBER_QUOTA_REACHED'
  | 'PAYMENT_PROVIDER_UNAVAILABLE' | 'PAYMENT_DECLINED' | 'PAYMENT_AMOUNT_MISMATCH'
  | 'CLIENT_AMOUNT_IGNORED' | 'PAYMENT_ALREADY_PAID' | 'REFUND_LIMIT_EXCEEDED' | 'REFUND_FAILED'
  | 'PLAN_LIMIT_REACHED' | 'INSUFFICIENT_CREDITS' | 'PROMO_INVALID' | 'SUBSCRIPTION_PAST_DUE'
  | 'AI_PROVIDER_TIMEOUT' | 'AI_PROVIDER_ERROR' | 'AI_INVALID_OUTPUT' | 'AUDIO_TOO_LONG' | 'AI_EMERGENCY_DETECTED'
  | 'DOC_TOO_LARGE' | 'DOC_TYPE_UNSUPPORTED' | 'DOC_VIRUS_DETECTED' | 'DOC_NOT_FOUND'
  | 'EMAIL_PROVIDER_ERROR' | 'GEOCODING_FAILED' | 'PUSH_FAILED'
  | 'SYS_DB_ERROR' | 'SYS_TIMEOUT' | 'SYS_MAINTENANCE' | 'SYS_OFFLINE'

const SEC_CODES = new Set<ErrorCode>([
  'SEC_TENANT_VIOLATION', 'SEC_RATE_LIMITED', 'SEC_WEBHOOK_SIGNATURE',
  'SEC_WITHDRAWAL_LOCKED', 'SEC_CAPTCHA_FAILED',
])

const HTTP_CODES: Record<ErrorCode, number> = {
  VAL_INVALID_INPUT: 400, VAL_MISSING_FIELD: 400,
  AUTH_REQUIRED: 401, AUTH_INVALID_CREDENTIALS: 401, AUTH_LOCKED: 401,
  AUTH_2FA_REQUIRED: 401, AUTH_2FA_INVALID: 401, AUTH_EMAIL_NOT_VERIFIED: 401, AUTH_SESSION_EXPIRED: 401,
  PERM_DENIED: 404,
  SEC_TENANT_VIOLATION: 403, SEC_RATE_LIMITED: 429, SEC_WEBHOOK_SIGNATURE: 400,
  SEC_WITHDRAWAL_LOCKED: 429, SEC_CAPTCHA_FAILED: 400,
  SLOT_ALREADY_BOOKED: 409, SLOT_NOT_AVAILABLE: 409, CANCEL_TOO_LATE: 409,
  PRO_MONTHLY_LIMIT: 409, APPOINTMENT_NOT_ARRIVED: 409, SCHEDULE_CONFLICT: 409, SCHEDULE_HAS_APPOINTMENTS: 409,
  PRESCRIPTION_REQUIRED: 409, PRESCRIPTION_EXPIRED: 409, PRESCRIPTION_ALREADY_SHARED: 409,
  PRESCRIPTION_NOT_SIGNABLE: 409, PROFESSIONAL_NOT_VERIFIED: 409, SHARE_EXPIRED: 409, PDF_GENERATION_FAILED: 500,
  STOCK_INSUFFICIENT: 409, STOCK_CHANGED: 409, PHARMACY_CLOSED_FOR_RESERVATIONS: 409,
  PHARMACY_NOT_VERIFIED: 409, PREPARATION_BLOCKED: 409, WITHDRAWAL_CODE_INVALID: 400,
  WITHDRAWAL_LOCKED: 429, RESERVATION_EXPIRED: 409, CANCEL_NOT_ALLOWED: 409, CODE_POOL_EXHAUSTED: 500,
  MEMBER_NOT_VERIFIED: 409, CEILING_EXCEEDED: 409, COVERAGE_RULE_NOT_FOUND: 409, MEMBER_QUOTA_REACHED: 409,
  PAYMENT_PROVIDER_UNAVAILABLE: 503, PAYMENT_DECLINED: 402, PAYMENT_AMOUNT_MISMATCH: 409,
  CLIENT_AMOUNT_IGNORED: 400, PAYMENT_ALREADY_PAID: 409, REFUND_LIMIT_EXCEEDED: 403, REFUND_FAILED: 500,
  PLAN_LIMIT_REACHED: 402, INSUFFICIENT_CREDITS: 402, PROMO_INVALID: 409, SUBSCRIPTION_PAST_DUE: 402,
  AI_PROVIDER_TIMEOUT: 502, AI_PROVIDER_ERROR: 502, AI_INVALID_OUTPUT: 502, AUDIO_TOO_LONG: 400, AI_EMERGENCY_DETECTED: 400,
  DOC_TOO_LARGE: 400, DOC_TYPE_UNSUPPORTED: 400, DOC_VIRUS_DETECTED: 400, DOC_NOT_FOUND: 404,
  EMAIL_PROVIDER_ERROR: 502, GEOCODING_FAILED: 502, PUSH_FAILED: 502,
  SYS_DB_ERROR: 500, SYS_TIMEOUT: 503, SYS_MAINTENANCE: 503, SYS_OFFLINE: 503,
}

const RETRYABLE = new Set<ErrorCode>([
  'PAYMENT_PROVIDER_UNAVAILABLE', 'PDF_GENERATION_FAILED',
  'AI_PROVIDER_TIMEOUT', 'AI_PROVIDER_ERROR',
  'EMAIL_PROVIDER_ERROR', 'PUSH_FAILED', 'GEOCODING_FAILED',
  'SYS_DB_ERROR', 'SYS_TIMEOUT', 'SYS_MAINTENANCE',
])

/**
 * Retourne une Response JSON { ok: false, error: {...} } avec le bon status HTTP.
 * Le message "[CODE]" est un placeholder — le front résout le message lisible
 * depuis packages/shared/src/errors.ts (USER_MESSAGES).
 */
export function errRes(
  code: ErrorCode,
  cause?: string,
  entity?: string,
  meta?: Record<string, unknown>,
  requestId?: string,
): Response {
  const isSec = SEC_CODES.has(code)
  const body = {
    ok: false,
    error: {
      code,
      message: `[${code}]`,   // le front récupère le message depuis shared/errors.ts
      cause: isSec ? undefined : cause,
      http: HTTP_CODES[code] ?? 500,
      retryable: RETRYABLE.has(code),
      entity,
      meta,
    },
    request_id: requestId,
  }
  return new Response(JSON.stringify(body), {
    status: HTTP_CODES[code] ?? 500,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

export function okRes<T>(data: T, requestId?: string): Response {
  return new Response(JSON.stringify({ ok: true, data, request_id: requestId }), {
    status: 200,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}
